SET NOCOUNT ON;
PRINT '=== det_jurnal cols ===';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='det_jurnal' ORDER BY ORDINAL_POSITION;
PRINT '=== realisasi_pembayaran_det cols ===';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='realisasi_pembayaran_det' ORDER BY ORDINAL_POSITION;
PRINT '=== realisasi_pembayaran cols ===';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='realisasi_pembayaran' ORDER BY ORDINAL_POSITION;
